[package]
name = "ActorWebRTC"
version = "0.1.0"
authors = ["Liberxue <liberxue@gmail.com>"]
repository = "https://github.com/Liberxue/ActorWebRTC"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9.0"
